title: Researcher
url: "https://Copticoder.com"
baseurl: "/Ahmed Atya"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Page design by Ankit Sultana and edited by Ahmed Atya"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/Ahmed Atya/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
