title: Ahmed Atya
url: "https://Copticoder.github.io/"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"
remote_theme: ankitsultana/researcher@gem
tracking_id: #

footer: yes
footer_text: "Page design by Ankit Sultana and edited by Ahmed Atya"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
